# Generated by Django 4.2.7 on 2025-11-17 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("cache_value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "rate_cache",
            },
        ),
        migrations.CreateModel(
            name="CryptoRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crypto_id",
                    models.CharField(
                        choices=[
                            ("bitcoin", "Bitcoin (BTC)"),
                            ("ethereum", "Ethereum (ETH)"),
                            ("binancecoin", "Binance Coin (BNB)"),
                            ("cardano", "Cardano (ADA)"),
                            ("solana", "Solana (SOL)"),
                            ("ripple", "Ripple (XRP)"),
                            ("polkadot", "Polkadot (DOT)"),
                            ("dogecoin", "Dogecoin (DOGE)"),
                            ("tether", "Tether (USDT)"),
                            ("usd-coin", "USD Coin (USDC)"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("usd_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("cedis_price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "usd_to_cedis_rate",
                    models.DecimalField(decimal_places=4, default=12.5, max_digits=10),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_percentage_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "crypto_rates",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["crypto_id", "-timestamp"],
                        name="crypto_rate_crypto__eeee9b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-timestamp"],
                        name="crypto_rate_is_acti_87f20d_idx",
                    ),
                ],
            },
        ),
    ]
