# Generated by Django 4.2.7 on 2025-11-24 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0009_giftcardtransaction_device_fingerprint_and_more"),
        ("messaging", "0002_alter_message_sender"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("user1", "user2", "listing", "transaction")},
        ),
    ]
