# Generated by Django 4.2.7 on 2025-11-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_update_conversation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="File attachment (image, document, etc.)",
                null=True,
                upload_to="messages/attachments/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_name",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_size",
            field=models.IntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                help_text="Type of attachment: image, document, video, audio",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata (system notes, etc.)",
            ),
        ),
    ]
