# Generated by Django 4.2.7 on 2025-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_message_attachment_message_attachment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachment_name",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="attachment_size",
            field=models.IntegerField(
                blank=True, default=0, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                help_text="Type of attachment: image, document, video, audio",
                max_length=50,
                null=True,
            ),
        ),
    ]
