# Generated by Django 4.2.7 on 2025-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_alter_message_attachment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, help_text="When the message was last edited", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(
                default=False, help_text="Whether this message has been edited"
            ),
        ),
    ]
