# Generated by Django 4.2.7 on 2025-11-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0006_message_edited_at_message_is_edited"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        help_text="Emoji character (e.g., '👍', '❤️', '😂')",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="messaging.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "message_reactions",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "emoji"],
                        name="message_rea_message_7f9ef3_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="message_rea_user_id_096006_idx",
                    ),
                ],
                "unique_together": {("message", "user", "emoji")},
            },
        ),
    ]
