# Generated by Django 4.2.7 on 2025-11-20 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_name",
                    models.CharField(
                        help_text="Display name for the review", max_length=120
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email (optional, used for verification)",
                        max_length=254,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Review title/summary", max_length=200
                    ),
                ),
                ("comment", models.TextField(help_text="Detailed review comment")),
                (
                    "service_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Service quality rating",
                        null=True,
                    ),
                ),
                (
                    "speed_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Transaction speed rating",
                        null=True,
                    ),
                ),
                (
                    "support_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Customer support rating",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Feature on homepage"),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, help_text="Admin internal notes"),
                ),
                ("role", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Review",
                "verbose_name_plural": "User Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="marketing_u_status_42e615_idx",
                    ),
                    models.Index(
                        fields=["rating", "-created_at"],
                        name="marketing_u_rating_a1fbfa_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "-created_at"],
                        name="marketing_u_is_feat_4540bb_idx",
                    ),
                ],
            },
        ),
    ]
