# Generated by Django 4.2.7 on 2025-11-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = []
