# Generated by Django 4.2.7 on 2025-11-17 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_auto_20251116_1740"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="escrow_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("escrow_lock", "Escrow Lock"),
                            ("escrow_release", "Escrow Release"),
                            ("crypto_buy", "Crypto Buy"),
                            ("crypto_sell", "Crypto Sell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(default="cedis", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
