# Generated by Django 4.2.7 on 2025-11-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_cryptotransaction_admin_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="admin_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="crypto_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="momo_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="momo_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="network",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="user_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cryptotransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_admin", "Awaiting Admin Confirmation"),
                    ("completed", "Completed"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
