# Generated by Django 4.2.7 on 2025-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_add_crypto_transaction_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCryptoAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=50)),
                ("network", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this address"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_crypto_addresses",
                "ordering": ["crypto_id", "network"],
                "unique_together": {("crypto_id", "network")},
            },
        ),
    ]
