# Generated by Django 4.2.7 on 2025-11-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_add_admin_crypto_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot of crypto transfer transaction",
                null=True,
                upload_to="crypto_payment_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="cryptotransaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID/hash from crypto transfer",
                max_length=255,
            ),
        ),
    ]
