# Generated by Django 4.2.7 on 2025-11-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallets", "0006_cryptotransaction_payment_proof_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[("momo", "Mobile Money"), ("crypto", "Crypto")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_admin", "Awaiting Admin Confirmation"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=255, unique=True)),
                (
                    "momo_number",
                    models.CharField(
                        blank=True,
                        help_text="Mobile Money number used for deposit",
                        max_length=20,
                    ),
                ),
                (
                    "momo_name",
                    models.CharField(
                        blank=True,
                        help_text="Name on Mobile Money account",
                        max_length=255,
                    ),
                ),
                (
                    "momo_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("Vodafone", "Vodafone Cash"),
                            ("AirtelTigo", "AirtelTigo Money"),
                        ],
                        help_text="Mobile Money network",
                        max_length=20,
                    ),
                ),
                (
                    "momo_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from MoMo transfer",
                        max_length=255,
                    ),
                ),
                (
                    "momo_proof",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot of MoMo transaction",
                        null=True,
                        upload_to="deposits/momo_proofs/",
                    ),
                ),
                (
                    "crypto_id",
                    models.CharField(
                        blank=True,
                        help_text="Crypto type (e.g., bitcoin, ethereum)",
                        max_length=50,
                    ),
                ),
                (
                    "crypto_amount",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Amount in crypto",
                        max_digits=20,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="Network (e.g., TRC20, ERC20, BEP20)",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID/hash from crypto transfer",
                        max_length=255,
                    ),
                ),
                (
                    "crypto_proof",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot of crypto transaction",
                        null=True,
                        upload_to="deposits/crypto_proofs/",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, help_text="Admin notes about this deposit"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deposits",
                "ordering": ["-created_at"],
            },
        ),
    ]
