# Generated by Django 4.2.7 on 2025-11-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0008_withdrawal"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("momo", "Mobile Money"), ("bank", "Bank Account")],
                        max_length=10,
                    ),
                ),
                (
                    "momo_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("Vodafone", "Vodafone Cash"),
                            ("AirtelTigo", "AirtelTigo Money"),
                        ],
                        help_text="Mobile Money network",
                        max_length=20,
                    ),
                ),
                (
                    "momo_number",
                    models.CharField(
                        blank=True,
                        help_text="Admin's Mobile Money number",
                        max_length=20,
                    ),
                ),
                (
                    "momo_name",
                    models.CharField(
                        blank=True,
                        help_text="Name on Mobile Money account",
                        max_length=255,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=255),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=50
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, help_text="Bank branch", max_length=255
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="SWIFT code (for international)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active payment details for deposits"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for users (e.g., include reference number)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Payment Detail",
                "verbose_name_plural": "Admin Payment Details",
                "db_table": "admin_payment_details",
                "ordering": ["payment_type", "momo_network", "-is_active"],
            },
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="momo_name",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="momo_number",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="momo_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MTN", "MTN Mobile Money"),
                    ("Vodafone", "Vodafone Cash"),
                    ("AirtelTigo", "AirtelTigo Money"),
                ],
                help_text="Mobile Money network used (from admin payment details)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="momo_proof",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot of MoMo transaction (user's payment proof)",
                null=True,
                upload_to="deposits/momo_proofs/",
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="momo_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID from MoMo transfer (user's payment proof)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="admin_payment_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin payment detail used for this deposit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposits",
                to="wallets.adminpaymentdetails",
            ),
        ),
    ]
