# Generated by Django 4.2.7 on 2025-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0009_adminpaymentdetails_remove_deposit_momo_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admincryptoaddress",
            options={
                "ordering": ["crypto_id", "network"],
                "verbose_name": "Admin Crypto Address",
                "verbose_name_plural": "Admin Crypto Addresses",
            },
        ),
        migrations.AlterField(
            model_name="admincryptoaddress",
            name="address",
            field=models.CharField(
                help_text="Enter the crypto address for receiving deposits",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="admincryptoaddress",
            name="crypto_id",
            field=models.CharField(
                choices=[
                    ("bitcoin", "Bitcoin (BTC)"),
                    ("ethereum", "Ethereum (ETH)"),
                    ("tether", "Tether (USDT)"),
                    ("usd-coin", "USD Coin (USDC)"),
                    ("binancecoin", "Binance Coin (BNB)"),
                    ("cardano", "Cardano (ADA)"),
                    ("solana", "Solana (SOL)"),
                    ("ripple", "Ripple (XRP)"),
                    ("polkadot", "Polkadot (DOT)"),
                    ("dogecoin", "Dogecoin (DOGE)"),
                    ("litecoin", "Litecoin (LTC)"),
                    ("chainlink", "Chainlink (LINK)"),
                    ("polygon", "Polygon (MATIC)"),
                    ("avalanche", "Avalanche (AVAX)"),
                ],
                help_text="Select the cryptocurrency type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="admincryptoaddress",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Only active addresses are shown to users"
            ),
        ),
        migrations.AlterField(
            model_name="admincryptoaddress",
            name="network",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin Network (BTC)"),
                    ("ERC20", "Ethereum Network (ERC20)"),
                    ("TRC20", "Tron Network (TRC20)"),
                    ("BEP20", "Binance Smart Chain (BEP20)"),
                    ("SOL", "Solana Network (SOL)"),
                    ("MATIC", "Polygon Network (MATIC)"),
                    ("AVAX", "Avalanche Network (AVAX)"),
                    ("ARBITRUM", "Arbitrum One"),
                    ("OPTIMISM", "Optimism"),
                    ("BASE", "Base"),
                ],
                help_text="Select the blockchain network",
                max_length=20,
            ),
        ),
    ]
