# Generated by Django 4.2.7 on 2025-11-21 13:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0010_alter_admincryptoaddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Withdrawal fee charged",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount deducted (amount + fee)",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount requested by user (before fees)",
                max_digits=20,
            ),
        ),
    ]
