# Generated by Django 4.2.7 on 2025-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0011_withdrawal_fee_withdrawal_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="momo_name",
            field=models.CharField(
                blank=True, help_text="Name on Mobile Money account", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="momo_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile Money number to receive withdrawal",
                max_length=20,
            ),
        ),
    ]
