# Generated by Django 4.2.7 on 2025-11-23 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallets", "0012_alter_withdrawal_momo_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount involved in this activity",
                        max_digits=20,
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("escrow_lock", "Escrow Lock"),
                            ("escrow_release", "Escrow Release"),
                            ("escrow_refund", "Escrow Refund"),
                            ("withdrawal", "Withdrawal"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference to related transaction",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after this activity",
                        max_digits=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Activity Log",
                "verbose_name_plural": "Wallet Activity Logs",
                "db_table": "wallet_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="wallet_logs_user_id_4e3172_idx",
                    ),
                    models.Index(
                        fields=["log_type", "-timestamp"],
                        name="wallet_logs_log_typ_d4bf3a_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="wallet_logs_transac_cabd20_idx"
                    ),
                ],
            },
        ),
    ]
