# Generated by Django 4.2.7 on 2026-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0013_walletlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
