# Generated by Django 4.2.7 on 2025-11-17 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORDER_COMPLETED", "Order Completed"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("DEPOSIT_RECEIVED", "Deposit Received"),
                            ("WITHDRAWAL_COMPLETED", "Withdrawal Completed"),
                            ("KYC_APPROVED", "KYC Approved"),
                            ("KYC_REJECTED", "KYC Rejected"),
                            ("SYSTEM", "System Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
