# Generated by Django 4.2.7 on 2025-11-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRANSACTION_APPROVED", "Transaction Approved"),
                    ("TRANSACTION_REJECTED", "Transaction Rejected"),
                    ("GIFT_CARD_ORDER_CREATED", "Gift Card Order Created"),
                    ("GIFT_CARD_ORDER_APPROVED", "Gift Card Order Approved"),
                    ("GIFT_CARD_ORDER_DECLINED", "Gift Card Order Declined"),
                    ("GIFT_CARD_ORDER_COMPLETED", "Gift Card Order Completed"),
                    ("GIFT_CARD_PROOF_UPLOADED", "Gift Card Proof Uploaded"),
                    ("ORDER_COMPLETED", "Order Completed"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("DEPOSIT_RECEIVED", "Deposit Received"),
                    ("WITHDRAWAL_COMPLETED", "Withdrawal Completed"),
                    ("KYC_APPROVED", "KYC Approved"),
                    ("KYC_REJECTED", "KYC Rejected"),
                    ("SYSTEM", "System Notification"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read", "-created_at"],
                name="notificatio_user_id_cba35e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="notificatio_user_id_611c58_idx"
            ),
        ),
    ]
