# Generated by Django 4.2.7 on 2025-11-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_related_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRANSACTION_CREATED", "Transaction Created"),
                    ("TRANSACTION_APPROVED", "Transaction Approved"),
                    ("TRANSACTION_REJECTED", "Transaction Rejected"),
                    ("GIFT_CARD_ORDER_CREATED", "Gift Card Order Created"),
                    ("GIFT_CARD_ORDER_APPROVED", "Gift Card Order Approved"),
                    ("GIFT_CARD_ORDER_DECLINED", "Gift Card Order Declined"),
                    ("GIFT_CARD_ORDER_COMPLETED", "Gift Card Order Completed"),
                    ("GIFT_CARD_PROOF_UPLOADED", "Gift Card Proof Uploaded"),
                    ("ORDER_COMPLETED", "Order Completed"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("DEPOSIT_RECEIVED", "Deposit Received"),
                    ("WITHDRAWAL_COMPLETED", "Withdrawal Completed"),
                    ("KYC_APPROVED", "KYC Approved"),
                    ("KYC_REJECTED", "KYC Rejected"),
                    ("SYSTEM", "System Notification"),
                ],
                max_length=50,
            ),
        ),
    ]
