# Generated by Django 4.2.7 on 2025-11-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardorder",
            name="order_type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="giftcardorder",
            name="proof_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="giftcard_proofs/"
            ),
        ),
    ]
