# Generated by Django 4.2.7 on 2025-11-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_giftcardorder_order_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this listing",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "gift_card_code",
                    models.CharField(
                        blank=True,
                        help_text="Gift card code (hidden until purchase)",
                        max_length=255,
                    ),
                ),
                (
                    "gift_card_pin",
                    models.CharField(
                        blank=True,
                        help_text="Gift card PIN if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "gift_card_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value of the gift card in original currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Original currency (USD, EUR, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "asking_price_cedis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price seller wants in GHS",
                        max_digits=10,
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, help_text="Whether price is negotiable"
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Proof of gift card ownership",
                        null=True,
                        upload_to="giftcard_listing_proofs/",
                    ),
                ),
                (
                    "proof_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the gift card"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("under_review", "Under Review"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, help_text="Number of times listing was viewed"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When listing expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="orders.giftcard",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_giftcard_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcard_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Listing",
                "verbose_name_plural": "Gift Card Listings",
                "db_table": "gift_card_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this transaction",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "agreed_price_cedis",
                    models.DecimalField(
                        decimal_places=2, help_text="Agreed price in GHS", max_digits=10
                    ),
                ),
                (
                    "escrow_amount_cedis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount held in escrow",
                        max_digits=10,
                    ),
                ),
                (
                    "gift_card_code",
                    models.CharField(
                        blank=True,
                        help_text="Gift card code provided by seller",
                        max_length=255,
                    ),
                ),
                (
                    "gift_card_pin",
                    models.CharField(
                        blank=True,
                        help_text="Gift card PIN if applicable",
                        max_length=50,
                    ),
                ),
                ("card_provided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Buyer has verified the gift card works",
                    ),
                ),
                (
                    "buyer_verification_notes",
                    models.TextField(
                        blank=True, help_text="Buyer's verification notes"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("payment_received", "Payment Received (Escrow)"),
                            ("card_provided", "Card Provided by Seller"),
                            ("verifying", "Buyer Verifying"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("has_dispute", models.BooleanField(default=False)),
                (
                    "dispute_reason",
                    models.TextField(blank=True, help_text="Reason for dispute"),
                ),
                ("dispute_resolved", models.BooleanField(default=False)),
                (
                    "dispute_resolution",
                    models.TextField(
                        blank=True, help_text="Admin resolution of dispute"
                    ),
                ),
                ("dispute_resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcard_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute_resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_giftcard_transaction_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="orders.giftcardlisting",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcard_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Transaction",
                "verbose_name_plural": "Gift Card Transactions",
                "db_table": "gift_card_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("invalid_code", "Invalid/Non-working Gift Card"),
                            ("wrong_amount", "Wrong Gift Card Amount"),
                            ("expired_card", "Expired Gift Card"),
                            ("already_used", "Gift Card Already Used"),
                            ("seller_not_responding", "Seller Not Responding"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the dispute"),
                ),
                (
                    "evidence_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of image URLs as evidence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund_buyer", "Refund Buyer"),
                            ("release_to_seller", "Release to Seller"),
                            ("partial_refund", "Partial Refund"),
                            ("no_action", "No Action Required"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, help_text="Admin notes on resolution"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_giftcard_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcard_disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_giftcard_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="orders.giftcardtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Dispute",
                "verbose_name_plural": "Gift Card Disputes",
                "db_table": "gift_card_disputes",
                "ordering": ["-created_at"],
            },
        ),
    ]
