# Generated by Django 4.2.7 on 2025-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_giftcardlisting_giftcardtransaction_giftcarddispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcarddispute",
            name="evidence_required",
            field=models.BooleanField(
                default=True, help_text="Evidence is required for dispute resolution"
            ),
        ),
        migrations.AddField(
            model_name="giftcarddispute",
            name="fraud_indicators",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Automated fraud detection indicators",
            ),
        ),
        migrations.AddField(
            model_name="giftcarddispute",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                help_text="Dispute priority level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="giftcarddispute",
            name="verification_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of verification attempts made"
            ),
        ),
        migrations.AlterField(
            model_name="giftcarddispute",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the dispute - REQUIRED: Explain what went wrong, when you discovered the issue, and any steps you've taken"
            ),
        ),
        migrations.AlterField(
            model_name="giftcarddispute",
            name="evidence_images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of image URLs as evidence - REQUIRED: Screenshots showing the issue (e.g., error messages, invalid code attempts)",
            ),
        ),
    ]
