# Generated by Django 4.2.7 on 2025-11-23 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_giftcarddispute_evidence_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardTransactionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star - Very Poor"),
                            (2, "2 Stars - Poor"),
                            (3, "3 Stars - Average"),
                            (4, "4 Stars - Good"),
                            (5, "5 Stars - Excellent"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about the transaction"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rating is visible to others",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rated_user",
                    models.ForeignKey(
                        help_text="User being rated (seller)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        help_text="User who gave the rating (buyer)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="Transaction this rating is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="orders.giftcardtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Rating",
                "verbose_name_plural": "Transaction Ratings",
                "db_table": "gift_card_transaction_ratings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rated_user", "rating"],
                        name="gift_card_t_rated_u_aa929a_idx",
                    ),
                    models.Index(
                        fields=["transaction"], name="gift_card_t_transac_2fe36e_idx"
                    ),
                ],
            },
        ),
    ]
