# Generated by Django 4.2.7 on 2025-11-23 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0005_giftcardtransactionrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardtransaction",
            name="auto_release_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When to auto-release funds (1 hour after verification)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="buyer_verification_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for buyer to verify card", null=True
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="card_proof_image",
            field=models.ImageField(
                blank=True,
                help_text="Proof image of gift card provided by seller",
                null=True,
                upload_to="giftcard_transaction_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="seller_response_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for seller to provide card details",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GiftCardTransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Transaction Created"),
                            ("payment_locked", "Payment Locked in Escrow"),
                            ("card_provided", "Card Details Provided"),
                            ("card_verified", "Card Verified by Buyer"),
                            ("card_rejected", "Card Rejected by Buyer"),
                            ("dispute_created", "Dispute Created"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("cancelled", "Transaction Cancelled"),
                            ("completed", "Transaction Completed"),
                            ("auto_cancelled", "Auto-Cancelled (Seller Timeout)"),
                            ("auto_disputed", "Auto-Disputed (Buyer Timeout)"),
                            ("auto_released", "Auto-Released (Buyer Verified)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., amounts, status changes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="giftcard_transaction_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.giftcardtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Transaction Log",
                "verbose_name_plural": "Gift Card Transaction Logs",
                "db_table": "gift_card_transaction_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction", "-created_at"],
                        name="gift_card_t_transac_d8516d_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="gift_card_t_action_423ee9_idx",
                    ),
                ],
            },
        ),
    ]
