# Generated by Django 4.2.7 on 2025-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_giftcardtransaction_auto_release_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardlisting",
            name="card_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 hash of gift card code + PIN for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="giftcardlisting",
            name="proof_image_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Perceptual hash (pHash) of proof image for duplicate detection",
                max_length=64,
            ),
        ),
    ]
