# Generated by Django 4.2.7 on 2025-11-23 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_giftcardlisting_card_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCardDisputeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("dispute_created", "Dispute Created"),
                            ("evidence_uploaded", "Evidence Uploaded"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned to Admin"),
                            ("unassigned", "Unassigned from Admin"),
                            ("priority_changed", "Priority Changed"),
                            ("comment_added", "Comment Added"),
                            ("evidence_added", "Evidence Added"),
                            ("evidence_removed", "Evidence Removed"),
                            ("resolution_proposed", "Resolution Proposed"),
                            ("resolution_finalized", "Resolution Finalized"),
                            ("dispute_closed", "Dispute Closed"),
                            ("reopened", "Dispute Reopened"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Comment or notes about this action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., old_status, new_status, file_names)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.giftcarddispute",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="giftcard_dispute_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Card Dispute Log",
                "verbose_name_plural": "Gift Card Dispute Logs",
                "db_table": "gift_card_dispute_logs",
                "ordering": ["created_at"],
                "permissions": [
                    ("can_delete_dispute_log", "Can delete dispute log"),
                    ("can_modify_dispute_log", "Can modify dispute log"),
                ],
                "indexes": [
                    models.Index(
                        fields=["dispute", "created_at"],
                        name="gift_card_d_dispute_04ef5b_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="gift_card_d_action_648a07_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "created_at"],
                        name="gift_card_d_perform_69d273_idx",
                    ),
                ],
            },
        ),
    ]
