# Generated by Django 4.2.7 on 2025-11-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_giftcarddisputelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardtransaction",
            name="device_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="Device fingerprint for fraud detection",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="risk_factors",
            field=models.JSONField(
                blank=True, default=dict, help_text="Factors contributing to risk score"
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="risk_score",
            field=models.IntegerField(
                blank=True,
                help_text="Risk score calculated at transaction creation (0-100, higher = more risk)",
                null=True,
            ),
        ),
    ]
