# Generated by Django 4.2.7 on 2025-11-24 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0009_giftcardtransaction_device_fingerprint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="P2PServiceDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("invalid_email", "Invalid/Non-working Service Email"),
                            ("wrong_amount", "Wrong Service Amount"),
                            ("service_not_received", "Service Not Received"),
                            ("seller_not_responding", "Seller Not Responding"),
                            ("fraud", "Suspected Fraud"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the dispute"),
                ),
                (
                    "evidence_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of image URLs as evidence",
                    ),
                ),
                (
                    "evidence_required",
                    models.BooleanField(
                        default=True,
                        help_text="Evidence is required for dispute resolution",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Dispute priority level",
                        max_length=20,
                    ),
                ),
                (
                    "fraud_indicators",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Automated fraud detection indicators",
                    ),
                ),
                (
                    "verification_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts made"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund_buyer", "Refund Buyer"),
                            ("release_to_seller", "Release to Seller"),
                            ("partial_refund", "Partial Refund"),
                            ("no_action", "No Action Required"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, help_text="Admin notes on resolution"),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_p2p_service_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Dispute",
                "verbose_name_plural": "P2P Service Disputes",
                "db_table": "p2p_service_disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="P2PServiceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("cashapp", "CashApp"),
                            ("zelle", "Zelle"),
                        ],
                        help_text="Type of service (PayPal, CashApp, Zelle)",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this listing",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "service_email",
                    models.EmailField(
                        help_text="Email address for the service (PayPal email, CashApp tag, Zelle email)",
                        max_length=254,
                    ),
                ),
                (
                    "service_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount available in original currency (USD)",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Original currency (USD)",
                        max_length=10,
                    ),
                ),
                (
                    "asking_price_cedis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price seller wants in GHS",
                        max_digits=10,
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, help_text="Whether price is negotiable"
                    ),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Proof of service ownership (screenshot of balance, etc.)",
                        null=True,
                        upload_to="p2p_service_listing_proofs/",
                    ),
                ),
                (
                    "proof_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the service"
                    ),
                ),
                (
                    "service_email_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA256 hash of service email for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "proof_image_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Perceptual hash (pHash) of proof image for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("under_review", "Under Review"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, help_text="Number of times listing was viewed"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When listing expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_p2p_service_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Listing",
                "verbose_name_plural": "P2P Service Listings",
                "db_table": "p2p_service_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="P2PServiceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this transaction",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "agreed_price_cedis",
                    models.DecimalField(
                        decimal_places=2, help_text="Agreed price in GHS", max_digits=10
                    ),
                ),
                (
                    "escrow_amount_cedis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount held in escrow",
                        max_digits=10,
                    ),
                ),
                (
                    "service_email",
                    models.EmailField(
                        blank=True,
                        help_text="Service email provided by seller",
                        max_length=254,
                    ),
                ),
                (
                    "service_proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Proof image of service provided by seller",
                        null=True,
                        upload_to="p2p_service_transaction_proofs/",
                    ),
                ),
                ("service_provided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seller_response_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for seller to provide service details",
                        null=True,
                    ),
                ),
                (
                    "buyer_verification_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for buyer to verify service",
                        null=True,
                    ),
                ),
                (
                    "auto_release_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to auto-release funds (1 hour after verification)",
                        null=True,
                    ),
                ),
                (
                    "buyer_verified",
                    models.BooleanField(
                        default=False, help_text="Buyer has verified the service works"
                    ),
                ),
                (
                    "buyer_verification_notes",
                    models.TextField(
                        blank=True, help_text="Buyer's verification notes"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("payment_received", "Payment Received (Escrow)"),
                            ("service_provided", "Service Details Provided by Seller"),
                            ("verifying", "Buyer Verifying"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("has_dispute", models.BooleanField(default=False)),
                (
                    "dispute_reason",
                    models.TextField(blank=True, help_text="Reason for dispute"),
                ),
                ("dispute_resolved", models.BooleanField(default=False)),
                (
                    "dispute_resolution",
                    models.TextField(
                        blank=True, help_text="Admin resolution of dispute"
                    ),
                ),
                ("dispute_resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Risk score calculated at transaction creation (0-100, higher = more risk)",
                        null=True,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Factors contributing to risk score",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Device fingerprint for fraud detection",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute_resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_p2p_service_transaction_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="orders.p2pservicelisting",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Transaction",
                "verbose_name_plural": "P2P Service Transactions",
                "db_table": "p2p_service_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="P2PServiceTransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Transaction Created"),
                            ("payment_locked", "Payment Locked in Escrow"),
                            ("service_provided", "Service Details Provided"),
                            ("service_verified", "Service Verified by Buyer"),
                            ("service_rejected", "Service Rejected by Buyer"),
                            ("dispute_created", "Dispute Created"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("cancelled", "Transaction Cancelled"),
                            ("completed", "Transaction Completed"),
                            ("auto_cancelled", "Auto-Cancelled (Seller Timeout)"),
                            ("auto_disputed", "Auto-Disputed (Buyer Timeout)"),
                            ("auto_released", "Auto-Released (Buyer Verified)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this action"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p2p_service_transaction_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.p2pservicetransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Transaction Log",
                "verbose_name_plural": "P2P Service Transaction Logs",
                "db_table": "p2p_service_transaction_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="P2PServiceDisputeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("dispute_created", "Dispute Created"),
                            ("evidence_uploaded", "Evidence Uploaded"),
                            ("assigned_to_admin", "Assigned to Admin"),
                            ("admin_review_started", "Admin Review Started"),
                            ("admin_decision", "Admin Decision Made"),
                            ("resolution_applied", "Resolution Applied"),
                            ("dispute_closed", "Dispute Closed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this action"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.p2pservicedispute",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p2p_service_dispute_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Dispute Log",
                "verbose_name_plural": "P2P Service Dispute Logs",
                "db_table": "p2p_service_dispute_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="p2pservicedispute",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="orders.p2pservicetransaction",
            ),
        ),
        migrations.CreateModel(
            name="P2PServiceTransactionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star - Very Poor"),
                            (2, "2 Stars - Poor"),
                            (3, "3 Stars - Average"),
                            (4, "4 Stars - Good"),
                            (5, "5 Stars - Excellent"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about the transaction"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rated_user",
                    models.ForeignKey(
                        help_text="User being rated (seller)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        help_text="User who gave the rating (buyer)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_service_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="Transaction this rating is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="orders.p2pservicetransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P Service Transaction Rating",
                "verbose_name_plural": "P2P Service Transaction Ratings",
                "db_table": "p2p_service_transaction_ratings",
                "ordering": ["-created_at"],
                "unique_together": {("transaction", "rater")},
            },
        ),
        migrations.AddIndex(
            model_name="p2pservicetransaction",
            index=models.Index(
                fields=["buyer", "status"], name="p2p_service_buyer_i_f00070_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="p2pservicetransaction",
            index=models.Index(
                fields=["seller", "status"], name="p2p_service_seller__c11e34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="p2pservicetransaction",
            index=models.Index(
                fields=["listing", "status"], name="p2p_service_listing_aca070_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="p2pservicelisting",
            index=models.Index(
                fields=["service_type", "status"], name="p2p_service_service_a27a12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="p2pservicelisting",
            index=models.Index(
                fields=["seller", "status"], name="p2p_service_seller__dcda7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="p2pservicelisting",
            index=models.Index(
                fields=["service_email_hash"], name="p2p_service_service_4790cb_idx"
            ),
        ),
    ]
