# Generated by Django 4.2.7 on 2025-11-24 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0011_update_p2p_models_binance_style"),
    ]

    operations = [
        # First, update the migration state to remove old index that references service_email_hash
        # This must happen before adding fields to prevent Django from trying to recreate it
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='p2pservicelisting',
                    name='p2p_service_service_4790cb_idx',
                ),
            ],
        ),
        # Remove old indexes from database (if they exist)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS p2p_service_service_4790cb_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS orders_p2ps_service_type_status_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS orders_p2ps_seller_status_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS orders_p2ps_service_identifier_hash_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="p2pservicelisting",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("sell", "Sell - I have service to sell"),
                    ("buy", "Buy - I want to buy service"),
                ],
                default="sell",
                help_text="Whether this is a sell listing (seller has service) or buy listing (buyer wants service)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="p2pservicelisting",
            name="max_rate_cedis_per_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="For buy listings: Maximum rate buyer will pay (1 USD = X GHS). For sell listings: Not used.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicelisting",
            name="accepted_payment_methods",
            field=models.JSONField(
                default=list,
                help_text="For sell: List of payment methods seller accepts. For buy: Single payment method buyer will use. Format: [{'method': 'momo', 'provider': 'MTN', 'number': '0244123456', 'name': 'John Doe'}, ...]",
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicelisting",
            name="is_negotiable",
            field=models.BooleanField(
                default=False, help_text="Whether rate is negotiable"
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicelisting",
            name="rate_cedis_per_usd",
            field=models.DecimalField(
                decimal_places=4,
                default=12.0,
                help_text="For sell: Seller's rate (1 USD = X GHS). For buy: Buyer's max rate (highest rate buyer will pay)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicelisting",
            name="seller",
            field=models.ForeignKey(
                help_text="For sell listings: seller. For buy listings: buyer (person who wants to buy)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="p2p_service_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicetransaction",
            name="agreed_price_cedis",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Agreed price in GHS (calculated from amount_usd * listing.rate_cedis_per_usd)",
                max_digits=10,
            ),
        ),
    ]
