# Generated by Django 4.2.7 on 2025-11-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_add_listing_type_to_p2p"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="p2pservicelisting",
            name="orders_p2ps_service_type_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="p2pservicelisting",
            name="orders_p2ps_seller_status_idx",
        ),
        migrations.RenameIndex(
            model_name="p2pservicelisting",
            new_name="p2p_service_service_a987f2_idx",
            old_name="orders_p2ps_service_identifier_hash_idx",
        ),
    ]
