# Generated by Django 4.2.7 on 2025-11-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_add_listing_type_to_p2p"),
    ]

    operations = [
        # These operations were originally meant to remove/rename indexes
        # but the indexes may not exist in all environments (e.g., fresh deployments).
        # Making this a no-op migration to handle migration state differences.
    ]

