# Generated by Django 4.2.7 on 2025-11-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0013_remove_p2pservicelisting_orders_p2ps_service_type_status_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="p2pservicelisting",
            name="buyer_must_be_kyc_verified",
            field=models.BooleanField(
                default=False, help_text="Buyer must have KYC approved"
            ),
        ),
        migrations.AddField(
            model_name="p2pservicelisting",
            name="buyer_must_be_verified",
            field=models.BooleanField(
                default=False, help_text="Buyer must have verified email"
            ),
        ),
        migrations.AddField(
            model_name="p2pservicelisting",
            name="min_completed_trades",
            field=models.IntegerField(
                default=0,
                help_text="Minimum number of completed P2P trades required from buyers (0 = no requirement)",
            ),
        ),
        migrations.AddField(
            model_name="p2pservicelisting",
            name="required_payment_providers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Required payment providers buyer must use (filters accepted payment methods). Empty list = accept all. Format: ['MTN', 'Vodafone', 'AirtelTigo', 'Bank']. Only relevant for MoMo/bank methods.",
            ),
        ),
    ]
