# Generated by Django 4.2.7 on 2025-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_add_seller_application_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2pservicetransaction",
            name="escrow_released",
            field=models.BooleanField(
                default=False, help_text="Whether escrow has been released to seller"
            ),
        ),
        migrations.AddField(
            model_name="p2pservicetransaction",
            name="escrow_released_at",
            field=models.DateTimeField(
                blank=True, help_text="When escrow was released", null=True
            ),
        ),
    ]
