# Generated by Django 4.2.7 on 2025-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_add_escrow_release_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerapplication",
            name="proof_of_funds_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Perceptual hash of proof of funds image for duplicate detection",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sellerapplication",
            name="proof_of_funds_image",
            field=models.ImageField(
                blank=True,
                help_text="Proof of funds (required for new users without trade history)",
                null=True,
                upload_to="seller_applications/proof_of_funds/",
            ),
        ),
    ]
