# Generated by Django 4.2.7 on 2025-12-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_add_proof_of_funds_to_seller_application"),
        ("orders", "0019_increase_status_field_length"),
    ]

    operations = []
