# Generated by Django 4.2.7 on 2025-12-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_merge_20251210_1739"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Seller Application",
                "verbose_name_plural": "Seller Applications",
            },
        ),
        migrations.AddField(
            model_name="p2pservicetransaction",
            name="buyer_service_identifier",
            field=models.CharField(
                blank=True,
                help_text="Service identifier provided by buyer (where they want to receive service - for BUY listings)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicetransaction",
            name="auto_release_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When to auto-release funds (15 minutes after verification)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicetransaction",
            name="buyer_verification_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for buyer to verify service (15 minutes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="p2pservicetransaction",
            name="seller_response_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for seller to provide service details (15 minutes)",
                null=True,
            ),
        ),
    ]
