# Generated by Django 4.2.7 on 2025-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_add_buyer_service_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2pservicetransaction",
            name="seller_confirmation_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for seller to confirm payment receipt (15 minutes after buyer marks payment)",
                null=True,
            ),
        ),
    ]
