# Generated by Django 4.2.7 on 2026-01-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0022_add_seller_confirmation_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardtransaction",
            name="auto_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Was this transaction auto-cancelled due to timeout?",
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "seller_response_timeout",
                        "Seller did not respond within 24 hours",
                    ),
                    (
                        "buyer_verification_timeout",
                        "Buyer did not verify within deadline",
                    ),
                    ("admin_timeout", "Admin did not process within deadline"),
                    ("manual", "Manually cancelled by user"),
                ],
                help_text="Reason for cancellation if auto-cancelled",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="escrow_released",
            field=models.BooleanField(
                default=False, help_text="Have the escrowed funds been released?"
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="escrow_released_at",
            field=models.DateTimeField(
                blank=True, help_text="When were escrow funds released?", null=True
            ),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="seller_reminder_sent",
            field=models.BooleanField(
                default=False,
                help_text="Has reminder notification been sent to seller?",
            ),
        ),
        migrations.AlterField(
            model_name="giftcardtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("payment_received", "Payment Received (Escrow)"),
                    ("card_provided", "Card Provided by Seller"),
                    ("verifying", "Buyer Verifying"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                    ("auto_cancelled", "Auto-Cancelled (Seller Timeout)"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TransactionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("gift_card", "Gift Card Transaction"),
                            ("p2p_service", "P2P Service Transaction"),
                            ("crypto_buy", "Crypto Buy"),
                            ("crypto_sell", "Crypto Sell"),
                            ("escrow", "Escrow Operation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Transaction Created"),
                            ("payment_verified", "Payment Verified"),
                            ("payment_locked", "Payment Locked in Escrow"),
                            ("card_provided", "Gift Card Provided"),
                            ("buyer_verified", "Buyer Verified Item"),
                            ("funds_released", "Funds Released to Seller"),
                            ("auto_cancelled", "Auto-Cancelled by System"),
                            ("auto_released", "Auto-Released by System"),
                            ("dispute_opened", "Dispute Opened"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("cancelled", "Transaction Cancelled"),
                            ("refund_issued", "Refund Issued"),
                            ("approved_by_admin", "Approved by Admin"),
                            ("rejected_by_admin", "Rejected by Admin"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of requester", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent of requester"),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        blank=True, default=dict, help_text="Previous transaction state"
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="New transaction state after action",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Detailed notes about this action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (amounts, reasons, etc)",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="HMAC signature for log integrity",
                        max_length=256,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Audit Log",
                "verbose_name_plural": "Transaction Audit Logs",
                "db_table": "transaction_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["transaction_type", "transaction_id"],
                        name="idx_txn_type_id",
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="idx_action_timestamp"
                    ),
                    models.Index(
                        fields=["performed_by", "timestamp"], name="idx_user_timestamp"
                    ),
                ],
            },
        ),
    ]
