# Generated by Django 4.2.7 on 2025-11-22 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the device"),
                ),
                (
                    "user_agent",
                    models.TextField(help_text="Browser/device user agent string"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Hash of IP + user agent for quick lookup",
                        max_length=64,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this device session is active"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this device was first seen"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="When this device was last seen"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Approximate location (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_devices",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_device_user_id_14e9e9_idx",
                    ),
                    models.Index(
                        fields=["device_fingerprint"],
                        name="user_device_device__d2dc6a_idx",
                    ),
                ],
                "unique_together": {("user", "device_fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed Login Attempt"),
                            ("new_device", "New Device Login"),
                            ("device_revoked", "Device Session Revoked"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address where the event occurred"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the event (null for failed logins)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="security_lo_user_id_d40da4_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="security_lo_ip_addr_1ef27f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="security_lo_event_t_361f5d_idx",
                    ),
                ],
            },
        ),
    ]
