# Generated by Django 4.2.7 on 2025-11-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_userdevice_securitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("failed_login", "Failed Login Attempt"),
                    ("successful_login", "Successful Login"),
                    ("new_device", "New Device Login"),
                    ("device_revoked", "Device Session Revoked"),
                    ("password_change", "Password Change"),
                    ("two_factor_toggle", "Two-Factor Authentication Toggle"),
                    ("account_deactivated", "Account Deactivated"),
                    ("suspicious_activity", "Suspicious Activity"),
                ],
                max_length=50,
            ),
        ),
    ]
