# Generated by Django 4.2.7 on 2025-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_securitylog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disputes_against",
            field=models.IntegerField(
                default=0, help_text="Number of disputes filed against this user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="disputes_filed",
            field=models.IntegerField(
                default=0, help_text="Number of disputes filed by this user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="successful_trades",
            field=models.IntegerField(
                default=0, help_text="Number of successfully completed gift card trades"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.IntegerField(
                default=0,
                help_text="Trust score calculated from trades, disputes, and verification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score_override",
            field=models.IntegerField(
                blank=True,
                help_text="Admin override for trust score (if set, this value is used instead of calculated score)",
                null=True,
            ),
        ),
    ]
