# Generated by Django 4.2.7 on 2025-11-23 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_disputes_against_user_disputes_filed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Email verification status (required)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When email was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False, help_text="Phone verification status (optional)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When phone was verified", null=True
            ),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("failed_login", "Failed Login Attempt"),
                    ("successful_login", "Successful Login"),
                    ("new_device", "New Device Login"),
                    ("device_revoked", "Device Session Revoked"),
                    ("password_change", "Password Change"),
                    ("two_factor_toggle", "Two-Factor Authentication Toggle"),
                    ("account_deactivated", "Account Deactivated"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("email_verified", "Email Verified"),
                    ("phone_verified", "Phone Verified"),
                    ("ip_banned", "IP Address Banned"),
                    ("withdrawal_request", "Withdrawal Request"),
                    ("gift_card_listed", "Gift Card Listed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, help_text="Banned IP address", unique=True
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for banning this IP")),
                (
                    "banned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this IP was banned"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this ban is currently active"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for temporary bans",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this ban"
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who banned this IP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Banned IP Address",
                "verbose_name_plural": "Banned IP Addresses",
                "db_table": "banned_ips",
                "ordering": ["-banned_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "is_active"],
                        name="banned_ips_ip_addr_c09244_idx",
                    ),
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="banned_ips_is_acti_7cc559_idx",
                    ),
                ],
            },
        ),
    ]
