# Generated by Django 4.2.7 on 2025-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, help_text="Last time user was seen online", null=True
            ),
        ),
    ]
