# Generated by Django 4.2.7 on 2025-11-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_sell_p2p",
            field=models.BooleanField(
                default=False,
                help_text="Whether user can create sell listings for P2P services",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When seller application was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seller_status",
            field=models.CharField(
                choices=[
                    ("not_applied", "Not Applied"),
                    ("pending", "Application Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                ],
                default="not_applied",
                help_text="Current seller application status",
                max_length=20,
            ),
        ),
    ]
