# Generated by Django 4.2.7 on 2025-11-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("BUTTON_CLICK", "Button Click"),
                            ("FORM_SUBMIT", "Form Submit"),
                            ("TRADE_EXECUTED", "Trade Executed"),
                            ("WALLET_CREATED", "Wallet Created"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live_rate_source",
                    models.CharField(default="coinmarketcap", max_length=255),
                ),
                (
                    "escrow_percent",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
                ("support_contacts", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Settings",
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="UserMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_trades", models.IntegerField(default=0)),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_trade_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_metrics",
            },
        ),
    ]
