# Generated by Django 4.2.7 on 2025-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_fee_fixed_cedis",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in cedis for crypto withdrawals (applied in addition to percentage)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Percentage fee for crypto withdrawals (e.g., 0.5 = 0.5%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_max_fee_cedis",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Maximum fee in cedis for crypto withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_min_fee_cedis",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Minimum fee in cedis for crypto withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_fee_fixed",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in cedis for MoMo withdrawals (applied in addition to percentage)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Percentage fee for MoMo withdrawals (e.g., 1.0 = 1%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_max_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Maximum fee in cedis for MoMo withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_min_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Minimum fee in cedis for MoMo withdrawals",
                max_digits=10,
            ),
        ),
    ]
