# Generated by Django 4.2.7 on 2025-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_settings_crypto_withdrawal_fee_fixed_cedis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="crypto_withdrawal_fee_fixed_cedis",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="crypto_withdrawal_max_fee_cedis",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="crypto_withdrawal_min_fee_cedis",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="momo_withdrawal_fee_fixed",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="momo_withdrawal_max_fee",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="momo_withdrawal_min_fee",
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_fee_fixed_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in USD for crypto withdrawals (applied in addition to percentage)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_max_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Maximum fee in USD for crypto withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="crypto_withdrawal_min_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.16,
                help_text="Minimum fee in USD for crypto withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_fee_fixed_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in USD for MoMo withdrawals (applied in addition to percentage)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_max_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                help_text="Maximum fee in USD for MoMo withdrawals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="momo_withdrawal_min_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.08,
                help_text="Minimum fee in USD for MoMo withdrawals",
                max_digits=10,
            ),
        ),
    ]
