# Generated by Django 4.2.7 on 2025-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0004_remove_settings_crypto_withdrawal_fee_fixed_cedis_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="gift_cards_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable/disable gift card feature for users"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="special_requests_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable/disable special requests feature for users",
            ),
        ),
    ]
