# Generated by Django 4.2.7 on 2025-11-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_alter_settings_support_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="paypal_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable/disable PayPal service feature for users",
            ),
        ),
    ]
