# Generated by Django 4.2.7 on 2025-11-21 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_settings_paypal_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="admin_momo_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Admin MoMo details for Buy PayPal transactions (MTN, Vodafone, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="admin_paypal_email",
            field=models.EmailField(
                blank=True,
                help_text="Admin PayPal email/username where users should send PayPal funds when selling",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_buy_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("15.00"),
                help_text="Rate for buying PayPal balance (1 USD = X GHS). What users pay us when they buy PayPal.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_sell_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("14.50"),
                help_text="Rate for selling PayPal balance (1 USD = X GHS). What we pay users when they sell PayPal.",
                max_digits=10,
            ),
        ),
    ]
