# Generated by Django 4.2.7 on 2025-11-22 02:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_settings_admin_momo_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="admin_cashapp_tag",
            field=models.CharField(
                blank=True,
                help_text="Admin CashApp $tag where users should send CashApp funds when selling",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_buy_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("15.00"),
                help_text="Rate for buying CashApp balance (1 USD = X GHS). What users pay us when they buy CashApp.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable/disable CashApp service feature for users",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_sell_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("14.50"),
                help_text="Rate for selling CashApp balance (1 USD = X GHS). What we pay users when they sell CashApp.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_transaction_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Percentage fee for CashApp Buy/Sell transactions (e.g., 1.0 = 1%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_transaction_fixed_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in USD for CashApp Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_transaction_max_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                help_text="Maximum fee in USD for CashApp Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="cashapp_transaction_min_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.08,
                help_text="Minimum fee in USD for CashApp Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_transaction_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Percentage fee for PayPal Buy/Sell transactions (e.g., 1.0 = 1%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_transaction_fixed_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in USD for PayPal Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_transaction_max_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                help_text="Maximum fee in USD for PayPal Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="paypal_transaction_min_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.08,
                help_text="Minimum fee in USD for PayPal Buy/Sell transactions",
                max_digits=10,
            ),
        ),
    ]
