# Generated by Django 4.2.7 on 2025-11-22 04:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0009_settings_admin_cashapp_tag_settings_cashapp_buy_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="admin_zelle_email",
            field=models.EmailField(
                blank=True,
                help_text="Admin Zelle email/phone where users should send Zelle funds when selling",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_buy_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("15.00"),
                help_text="Rate for buying Zelle balance (1 USD = X GHS). What users pay us when they buy Zelle.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable/disable Zelle service feature for users"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_sell_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("14.50"),
                help_text="Rate for selling Zelle balance (1 USD = X GHS). What we pay users when they sell Zelle.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_transaction_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Percentage fee for Zelle Buy/Sell transactions (e.g., 1.0 = 1%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_transaction_fixed_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee in USD for Zelle Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_transaction_max_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                help_text="Maximum fee in USD for Zelle Buy/Sell transactions",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="zelle_transaction_min_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.08,
                help_text="Minimum fee in USD for Zelle Buy/Sell transactions",
                max_digits=10,
            ),
        ),
    ]
