# Generated by Django 4.2.7 on 2025-11-21 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0002_contactenquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Unique reference for this request",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("money_transfer", "Money Transfer (International)"),
                            ("custom_payment", "Custom Payment Method"),
                            ("bulk_transaction", "Bulk Transaction"),
                            ("escrow_service", "Escrow Service"),
                            ("crypto_service", "Custom Crypto Service"),
                            ("other", "Other Service"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the request", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what you need"),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated amount involved (if applicable)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS",
                        help_text="Currency (GHS, USD, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("quoted", "Quote Provided"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal admin notes (not visible to user)",
                    ),
                ),
                (
                    "quote_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quote provided to user",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(
                        blank=True, help_text="Quote details/terms (visible to user)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_special_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_special_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Request",
                "verbose_name_plural": "Special Requests",
                "db_table": "special_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
