# Generated by Django 4.2.7 on 2025-11-21 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0003_specialrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this request",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receive", "Receive PayPal Funds"),
                            ("send", "Send PayPal Funds"),
                        ],
                        help_text="Receive or send PayPal funds",
                        max_length=20,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in USD", max_digits=20
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(help_text="PayPal email address", max_length=254),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient name (if sending)",
                        max_length=255,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Recipient PayPal email (if sending)",
                        max_length=254,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Transaction description/purpose"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("quoted", "Quote Provided"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal admin notes (not visible to user)",
                    ),
                ),
                (
                    "quote_amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quote in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD to GHS rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(
                        blank=True, help_text="Quote details/terms (visible to user)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_paypal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_paypal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Request",
                "verbose_name_plural": "PayPal Requests",
                "db_table": "paypal_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
