# Generated by Django 4.2.7 on 2025-11-21 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0004_paypalrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this transaction",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sell", "Sell PayPal Balance"),
                            ("buy", "Buy PayPal Balance"),
                        ],
                        help_text="Buy or sell PayPal balance",
                        max_length=20,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in USD", max_digits=20
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(
                        help_text="User's PayPal email address", max_length=254
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(help_text="MoMo, Bank, etc.", max_length=50),
                ),
                (
                    "payment_details",
                    models.TextField(
                        help_text="Account number, MoMo number, bank details, etc."
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "admin_paypal_email",
                    models.EmailField(
                        blank=True,
                        help_text="Admin PayPal email for transaction",
                        max_length=254,
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Screenshot or proof of payment",
                        null=True,
                        upload_to="paypal_payment_proofs/",
                    ),
                ),
                (
                    "payment_proof_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about payment proof"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("details", "Details Submitted"),
                            ("payment_proof", "Payment Proof Uploaded"),
                            ("verified", "Payment Verified"),
                            ("completed", "Completed"),
                        ],
                        default="details",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("payment_sent", "Payment Sent (Awaiting Verification)"),
                            ("payment_verified", "Payment Verified"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD to GHS rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "is_paypal_balance_only",
                    models.BooleanField(
                        default=True,
                        help_text="Transaction must be from PayPal balance only, not bank/third party",
                    ),
                ),
                (
                    "user_confirmed_balance_only",
                    models.BooleanField(
                        default=False,
                        help_text="User confirmed they are sending from PayPal balance only",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_sent_at", models.DateTimeField(blank=True, null=True)),
                ("payment_verified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_paypal_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Transaction",
                "verbose_name_plural": "PayPal Transactions",
                "db_table": "paypal_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
