# Generated by Django 4.2.7 on 2025-11-22 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0005_paypaltransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalPurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this request",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name/description of the item or service",
                        max_length=500,
                    ),
                ),
                (
                    "item_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the item or service (if available)",
                    ),
                ),
                (
                    "item_description",
                    models.TextField(
                        help_text="Detailed description of what you want to purchase"
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount needed in USD",
                        max_digits=20,
                    ),
                ),
                (
                    "recipient_paypal_email",
                    models.EmailField(
                        help_text="PayPal email of the seller/merchant", max_length=254
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the recipient (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True,
                        help_text="Shipping address if physical item (optional)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="momo", help_text="MoMo, Bank, etc.", max_length=50
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True,
                        help_text="MoMo number, account details, etc. (if known)",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Request priority",
                        max_length=20,
                    ),
                ),
                (
                    "urgency_reason",
                    models.TextField(
                        blank=True, help_text="Why this is urgent (if applicable)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("quoted", "Quote Provided"),
                            ("approved", "Approved"),
                            ("payment_pending", "Awaiting User Payment"),
                            ("processing", "Processing Purchase"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "quote_amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount user needs to pay in cedis",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Exchange rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in cedis",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the quote or process"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Proof of PayPal payment made by admin",
                        null=True,
                        upload_to="paypal_purchase_proofs/",
                    ),
                ),
                (
                    "delivery_tracking",
                    models.CharField(
                        blank=True,
                        help_text="Tracking number or delivery info (if applicable)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When user paid admin", null=True
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When admin made the PayPal payment",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin assigned to handle this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_paypal_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_paypal_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Purchase Request",
                "verbose_name_plural": "PayPal Purchase Requests",
                "db_table": "paypal_purchase_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
