# Generated by Django 4.2.7 on 2025-11-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0006_paypalpurchaserequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashAppTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this transaction",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sell", "Sell CashApp Balance"),
                            ("buy", "Buy CashApp Balance"),
                        ],
                        help_text="Buy or sell CashApp balance",
                        max_length=20,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in USD", max_digits=20
                    ),
                ),
                (
                    "cashapp_tag",
                    models.CharField(
                        help_text="User's CashApp $tag or email", max_length=100
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(help_text="MoMo, Bank, etc.", max_length=50),
                ),
                (
                    "payment_details",
                    models.TextField(
                        help_text="Account number, MoMo number, bank details, etc."
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "admin_cashapp_tag",
                    models.CharField(
                        blank=True,
                        help_text="Admin CashApp $tag for transaction",
                        max_length=100,
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Screenshot or proof of payment",
                        null=True,
                        upload_to="cashapp_payment_proofs/",
                    ),
                ),
                (
                    "payment_proof_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about payment proof"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("details", "Details Submitted"),
                            ("payment_proof", "Payment Proof Uploaded"),
                            ("verified", "Payment Verified"),
                            ("completed", "Completed"),
                        ],
                        default="details",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("payment_sent", "Payment Sent (Awaiting Verification)"),
                            ("payment_verified", "Payment Verified"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD to GHS rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "is_cashapp_balance_only",
                    models.BooleanField(
                        default=True,
                        help_text="Transaction must be from CashApp balance only, not bank/third party",
                    ),
                ),
                (
                    "user_confirmed_balance_only",
                    models.BooleanField(
                        default=False,
                        help_text="User confirmed they are sending from CashApp balance only",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_sent_at", models.DateTimeField(blank=True, null=True)),
                ("payment_verified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashapp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_cashapp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CashApp Transaction",
                "verbose_name_plural": "CashApp Transactions",
                "db_table": "cashapp_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashAppRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this request",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receive", "Receive CashApp Funds"),
                            ("send", "Send CashApp Funds"),
                        ],
                        help_text="Receive or send CashApp funds",
                        max_length=20,
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in USD", max_digits=20
                    ),
                ),
                (
                    "cashapp_tag",
                    models.CharField(
                        help_text="CashApp $tag or email address", max_length=100
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient name (if sending)",
                        max_length=255,
                    ),
                ),
                (
                    "recipient_tag",
                    models.CharField(
                        blank=True,
                        help_text="Recipient CashApp $tag (if sending)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Transaction description/purpose"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("quoted", "Quote Provided"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal admin notes (not visible to user)",
                    ),
                ),
                (
                    "quote_amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quote in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="USD to GHS rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in GHS",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(
                        blank=True, help_text="Quote details/terms (visible to user)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cashapp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cashapp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashapp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CashApp Request",
                "verbose_name_plural": "CashApp Requests",
                "db_table": "cashapp_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashAppPurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference for this request",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name/description of the item or service",
                        max_length=500,
                    ),
                ),
                (
                    "item_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the item or service (if available)",
                    ),
                ),
                (
                    "item_description",
                    models.TextField(
                        help_text="Detailed description of what you want to purchase"
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount needed in USD",
                        max_digits=20,
                    ),
                ),
                (
                    "recipient_cashapp_tag",
                    models.CharField(
                        help_text="CashApp $tag of the seller/merchant", max_length=100
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the recipient (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True,
                        help_text="Shipping address if physical item (optional)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="momo", help_text="MoMo, Bank, etc.", max_length=50
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True,
                        help_text="MoMo number, account details, etc. (if known)",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Request priority",
                        max_length=20,
                    ),
                ),
                (
                    "urgency_reason",
                    models.TextField(
                        blank=True, help_text="Why this is urgent (if applicable)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("quoted", "Quote Provided"),
                            ("approved", "Approved"),
                            ("payment_pending", "Awaiting User Payment"),
                            ("processing", "Processing Purchase"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "quote_amount_cedis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount user needs to pay in cedis",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Exchange rate used",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service fee in cedis",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "quote_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the quote or process"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Proof of CashApp payment made by admin",
                        null=True,
                        upload_to="cashapp_purchase_proofs/",
                    ),
                ),
                (
                    "delivery_tracking",
                    models.CharField(
                        blank=True,
                        help_text="Tracking number or delivery info (if applicable)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When user paid admin", null=True
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When admin made the CashApp payment",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin assigned to handle this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cashapp_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cashapp_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashapp_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CashApp Purchase Request",
                "verbose_name_plural": "CashApp Purchase Requests",
                "db_table": "cashapp_purchase_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
