# Generated by Django 4.2.7 on 2025-11-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="category",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("trading", "Trading"),
                    ("wallets", "Wallets"),
                    ("security", "Security"),
                ],
                max_length=50,
            ),
        ),
    ]
