release: python manage.py migrate --no-input; python manage.py migrate --no-input --run-syncdb
web: python manage.py collectstatic --no-input; gunicorn --bind 0.0.0.0:$PORT --workers 1 config.wsgi:application
